stages:
- package
- test
- doc
- push


build:
  image: gitlab/dind:latest
  stage: package
  before_script:
    - export
    - mkdir -p $HOME/.docker/
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"$HTTP_PROXY\", \"httpsProxy\": \"$HTTPS_PROXY\", \"noProxy\": \"$NO_PROXY\" } } }" > $HOME/.docker/config.json'
  script:
    - docker build --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTP_PROXY --build-arg NO_PROXY=$NO_PROXY -t $CI_REGISTRY_IMAGE:tmp .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:tmp
  only:
    - master

test:
  image: docker:stable
  stage: test
  services:
    - docker:dind
  script:
    - docker run --name $DOCKER_IMAGE_BUILD_TAG_ID $CI_REGISTRY_IMAGE:tmp coverage run -m pytest 
    - docker run --name $DOCKER_IMAGE_BUILD_TAG_ID $CI_REGISTRY_IMAGE:tmp coverage report
    - docker cp $DOCKER_IMAGE_BUILD_TAG_ID:/usr/app/my_app/coverage $CI_PROJECT_DIR/coverage
  when: on_success
  artifacts:
    paths:
      - coverage/htmlcov/*
    reports:
      junit: coverage/coverage.xml
  only:
    - master

doc:
  image: docker:stable
  stage: doc
  services: 
    - docker:dind
  script:
    - docker run --name $DOCKER_IMAGE_BUILD_TAG_ID $CI_REGISTRY_IMAGE:tmp mccabe --min 5 --dot mccabe.py | dot -Tpng -o doc/complexity.png
    - docker run --name $DOCKER_IMAGE_BUILD_TAG_ID $CI_REGISTRY_IMAGE:tmp pyreverse -p my_app | | dot -Tpng -o doc/diagram.png  
    - docker cp $DOCKER_IMAGE_BUILD_TAG_ID:/usr/app/my_app/doc $CI_PROJECT_DIR/doc
    - docker rm $DOCKER_IMAGE_BUILD_TAG_ID
  when: on_success
  artifacts:
    paths: 
      - doc/complexity.png
      - doc/diagram.png

push:
  image: docker:stable
  stage: push
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker image pull $CI_REGISTRY_IMAGE:tmp
    - docker image tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker image tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  only:
    - master
